sudo: required
language: rust
dist: trusty
services:
  - docker
env: TARGET=x86_64-unknown-linux-musl DOCKER=musl
addons:
  ssh_known_hosts: xev.maven-group.org

install:
  - rustup target add x86_64-unknown-linux-musl
  - pushd site
  - bundle install
  - popd
script:
  - ./ci/local

after_failure:
  - find . -name config.log -print -exec cat {} \;
before_deploy:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
      openssl aes-256-cbc -K $encrypted_e22c542db632_key -iv $encrypted_e22c542db632_iv -in id_ed25519.enc -out /tmp/id_ed25519 -d ;
      chmod 600 /tmp/id_ed25519 ;
      eval "$(ssh-agent -s)" ;
      ssh-add /tmp/id_ed25519 ;
    fi
deploy:
  provider: script
  skip_cleanup: true
  script:
    - scp target/metazite.tar.gz brian@xev.maven-group.org:/opt/metaz.io/metazite.tar.gz
  on:
    branch: master
