[package]
name = "metazite"
version = "0.1.0"
authors = ["Brian Olsen <brian@maven-group.org>"]
build = "build.rs"

[dependencies]
addr2line = "0.5.0"
bodyparser = "0.7"
chrono = "0.4"
hyper = "0.10"
iron = "0.5.1"
lru = "0.1.4"
mount = "0.3.0"
owning_ref = "0.3.3"
persistent = "0.3"
plugin = "0.2"
prometheus = "0.3.2"
protobuf = "1.4.1"
router = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.3"
url = "1.1"
urlencoded = "0.5.0"
zip = "0.2"

[dependencies.uuid]
version = "0.5"
features = ["v4"]

[dependencies.maxminddb]
git = "https://github.com/griff/maxminddb-rust"
branch = "feature/byte-reader"

[build-dependencies]
protoc-rust = "1.4.1"
